import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
        </div>
        <div>
          <h1>Test H1</h1>
          <h2>Test H2</h2>
          <h3>Test H3</h3>
          <h4>Test H4</h4>
          <p className="technique">Technique</p>
          <p>Paragraph</p>
          <span className="material-symbols-outlined">search</span>
          <span className="material-symbols-rounded">close</span>
          <span className="material-symbols-rounded">arrow_back_ios</span>
          <span className="material-symbols-rounded">arrow_forward_ios</span>
          <span className="material-symbols-rounded">arrow_outward</span>
        </div>
      </main>
    </>
  );
}
